<div class="api-data-wrapper soundcloud-api-data" onclick="SK_addSoundcloudData('{{SOUNDCLOUD_TITLE}}','{{SOUNDCLOUD_URI}}');">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="40px" align="left" valign="middle">
            <img class="thumbnail" src="{{SOUNDCLOUD_THUMBNAIL}}" width="32px" height="32px" valign="middle" alt="Image">
        </td>

        <td align="left" valign="middle">
            <div class="name">
                {{SOUNDCLOUD_TITLE}}
            </div>

            <div class="info">
                {{SOUNDCLOUD_GENRE}}
            </div>
        </td>
    </tr>
    </table>
</div>