<div class="api-data-wrapper youtube-api-data" onclick="SK_addYoutubeData('{{YOUTUBE_ID}}','{{YOUTUBE_TITLE}}');">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="40px" align="left" valign="middle">
            <img class="thumbnail" src="{{YOUTUBE_THUMBNAIL_URL}}" width="32px" height="32px" valign="middle" alt="Youtube">
        </td>
        
        <td align="left" valign="middle">
            <div class="name">
                {{YOUTUBE_TITLE}}
            </div>

            <div class="info">
                {{YOUTUBE_CATEGORY}}
            </div>
        </td>
    </tr>
    </table>
</div>