<div class="page-margin"></div>

<div class="float-left span59">
    <form class="create-group-form" method="post">
        <div class="form-container">
            <div class="form-header">@group_create_label@</div>

            <div class="form-input-wrapper">
                <label class="float-left span20">@group_name_label@:</label>
                
                <div class="input float-left span70">
                    <input type="text" value="@group_name_textarea_label@" placeholder="@group_name_textarea_label@" data-placeholder="@group_name_textarea_label@" onkeyup="SK_generateUsername(this.value);" data-copy-to=".group-name-input">
                    
                    <input class="group-name-input" type="hidden" name="group_name">
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            <div class="form-input-wrapper">
                <label class="float-left span20">@username_label@:</label>
                
                <div class="input float-left span70">
                    <input class="username-textinput" type="text" value="@group_username_textarea_label@" placeholder="@group_username_textarea_label@" data-placeholder="@group_username_textarea_label@" autocomplete="off" data-copy-to=".group-username-input" onkeyup="SK_checkUsername(this.value,0,'.check-username-result',true);">
                    
                    <input class="group-username-input" type="hidden" name="group_username">
                    
                    <div class="check-username-result"></div>
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            <div class="form-input-wrapper">
                <label class="float-left span20">
                    @about_label@:
                </label>
                
                <div class="input float-left span70">
                    <textarea class="auto-grow-input" valign="top" name="group_about" placeholder="@group_description_textarea_label@" data-placeholder="@group_description_textarea_label@">@group_description_textarea_label@</textarea>
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            <div class="form-input-wrapper">
                <label class="float-left span20">
                    @privacy_label@:
                </label>
                
                <div class="input float-left span70">
                    <div style="margin-bottom: 15px;">
                        <input valign="top" type="radio" name="group_privacy" value="open">

                        <label><i class="icon-globe"></i> @open_group@</label>

                        <div class="short-descr">
                            @open_group_description@.
                        </div>
                    </div>
                    
                    <div style="margin-bottom: 15px;">
                        <input valign="top" type="radio" name="group_privacy" value="closed" checked>

                        <label><i class="icon-lock"></i> @closed_group@</label>

                        <div class="short-descr">
                            @closed_group_description@.
                        </div>
                    </div>
                    
                    <div style="margin-bottom: 10px;">
                        <input valign="top" type="radio" name="group_privacy" value="secret">

                        <label><i class="icon-shield"></i> @secret_group@</label>
                        
                        <div class="short-descr">
                            @secret_group_description@.
                        </div>
                    </div>
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            <div class="form-input-wrapper">
                <button class="active">
                    @group_create_label@
                </button>
            </div>
        </div>
    </form>
</div>

<div class="float-right span40">
    <div class="list-wrapper">
        <div class="list-header">@group_intro_header@</div>
        
        <div class="list-column">
            <strong class="bold-500">@group_intro_list1_header@</strong>
            <br>
            @group_intro_list1_description@
        </div>
        
        <div class="list-column">
            <strong class="bold-500">@group_intro_list2_header@</strong>
            <br>
            @group_intro_list2_description@
        </div>
        
        <div class="list-column">
            <strong class="bold-500">@group_intro_list3_header@</strong>
            <br>
            @group_intro_list3_description@
        </div>
    </div>
</div>

<div class="float-clear"></div>

<script>
$(function () {
    $('form.create-group-form').ajaxForm({
        url: SK_source() + '?t=group&a=create',
        
        beforeSend: function() {
            $('form.create-group-form')
                .find('button')
                    .removeClass()
                    .text('@creating@...');
        },
        
        success: function(responseText) {
            
            if (responseText.status == 200) {
                window.location = responseText.url;
            }
            else {
                $('form.create-group-form')
                .find('button')
                    .addClass('active')
                    .text('@group_create_label@');
            }
        }
    });
});
</script>