<div class="comment-wrapper">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="40px" align="left" valign="top">
            <a href="{{PUBLISHER_USERNAME}}">
                <img class="avatar" src="{{PUBLISHER_THUMBNAIL_URL}}" width="32px" height="32px">
            </a>
        </td>
        <td align="left" valign="top">
            <div class="comment-textarea">
                <textarea class="auto-grow-input" name="text" placeholder="@comment_textarea_label@" data-placeholder="@comment_textarea_label@" data-height="24" onkeyup="postComment(this.value,{{STORY_ID}},{{PUBLISHER_ID}},event);">@comment_textarea_label@</textarea>
                <i class="icon-lightbulb progress-icon hide"></i>
            </div>
        </td>
    </tr>
    </table>
</div>