<div class="page-margin"></div>

<div class="float-left span50">
    <div class="list-wrapper">
	    <div class="list-header">
	        <div class="float-left">
	            @manage_pages_header_label@
	        </div>

	        <div class="float-right">
	            <a class="hover-line" href="{{CREATE_PAGE_URL}}" data-href="?tab1=create_page">
	                @page_create_label@
	            </a>
	        </div>

	        <div class="float-clear"></div>
	    </div>
	    
	    {{LIST_MANAGED_PAGES}}
	</div>
</div>

<div class="float-right span49">
    <div class="list-wrapper">
	    <div class="list-header">
	        <div class="float-left">
	            @manage_groups_header_label@
	        </div>

	        <div class="float-right">
	            <a class="hover-line" href="{{CREATE_GROUP_URL}}" data-href="?tab1=create_group">
	                @group_create_label@
	            </a>
	        </div>

	        <div class="float-clear"></div>
	    </div>
	    
	    {{LIST_MANAGED_GROUPS}}
	</div>
</div>

<div class="float-clear"></div>