<div class="page-margin"></div>
<div class="float-left span60 desktop-only">
    <h1>
        {{WELCOME_TO_SITENAME}}
    </h1>
    
    <div class="wc-feat-float">
        <i class="icon-group" style="font-size: 50px;"></i>
        <div class="feat-msg">
            <strong>@site_description@</strong>
            <p>
                @site_description_paragraph@
            </p>
        </div>
        <div class="float-clear"></div>
    </div>

    <div class="wc-feat-float">
        <i class="icon-tablet" style="font-size: 80px;"></i>
        <div class="feat-msg">
            <strong>@go_mobile_description@</strong>
            <p>
                @go_mobile_description_paragraph@
            </p>
        </div>
        <div class="float-clear"></div>
    </div>

    <div class="wc-feat-float">
        <i class="icon-globe" style="font-size: 70px;"></i>
        <div class="feat-msg">
            <strong>@trending_description@</strong>
            <p>
                @trending_description_paragraph@
            </p>
        </div>
        <div class="float-clear"></div>
    </div>
</div>
<div class="float-right span35">
    {{TAB_CONTENT}}

    <div class="fb-button">
        <a href="{{FACEBOOK_LOGIN_URL}}">
            <i class="icon-facebook"></i>
            <span>@connect_with_fb@</span>
        </a>
    </div>
</div>

<div class="float-clear"></div>
