<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">

    <title>{{CONFIG_SITE_TITLE}}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">

    <link rel="shortcut icon" href="{{CONFIG_SITE_URL}}/favicon.ico" />

    <link href="{{CONFIG_THEME_URL}}/css/style.css" rel="stylesheet">

    <link href="{{CONFIG_THEME_URL}}/css/style-1.1.css" rel="stylesheet">

    <link href="{{CONFIG_THEME_URL}}/css/style-1.2.css" rel="stylesheet">

    {{WELCOME_CSS_HTML}}

    <link href="{{CONFIG_THEME_URL}}/css/font-awesome/font-awesome.css" rel="stylesheet">
    
    <!--[if IE 7]>
        <link href="{{CONFIG_THEME_URL}}/css/font-awesome/font-awesome-ie7.css" rel="stylesheet">
    <![endif]-->

    <script src="{{CONFIG_THEME_URL}}/javascript/jquery.1.10.2.min.js"></script>

    <script src="{{CONFIG_THEME_URL}}/javascript/jquery-ui-1.10.4.custom.min.js"></script>

    <script src="{{CONFIG_THEME_URL}}/javascript/jquery.ui.touch-punch.min.js"></script>

    <script src="{{CONFIG_THEME_URL}}/javascript/jquery-timeago.js"></script>
    
    <script src="{{CONFIG_THEME_URL}}/javascript/jquery.form.min.js"></script>

    {{JS_SOURCES}}
    
    {{JS_SCRIPT}}
    
    {{CHAT_INITIATE_JS}}

    <script>
    function startPageLoadingBar() {
        $(".page-loading-bar")
            .show()
            .width((50 + Math.random() * 30) + "%");
    }
    function stopPageLoadingBar() {
        $(".page-loading-bar")
            .width("101%")
            .delay(200)
            .fadeOut(400, function() {
                $(this).width("0");
            });
    }

    $(document).on('click', '*[data-href]', function(e) {
        startPageLoadingBar();
    });
    </script>
</head>
<body data-rewrite="{{BODY_REWRITE_ATTR}}">
    {{HEADER}}

    <div class="page-loading-bar">
        <dd></dd>
        <dt></dt>
    </div>
    
    <div class="page-wrapper">
        {{PAGE_CONTENT}}
    </div>
    
    {{FOOTER}}
    
    {{CHAT}}
    
    <audio id="notification-sound" preload="auto">
        <source src="{{CONFIG_THEME_URL}}/sounds/notification.ogg" type="audio/ogg">
        <source src="{{CONFIG_THEME_URL}}/sounds/notification.mp3" type="audio/mpeg">
        <source src="{{CONFIG_THEME_URL}}/sounds/notification.wav" type="audio/wav">
    </audio>
    <script>
    $(function(){
        $('.update-alert').each(function() {
            var upd_num = $(this).text() * 1;

            if (upd_num == 0)
            {
                $(this).hide();
            }
        });
        $('.new-update-alert').each(function() {
            var upd_num = $(this).text() * 1;

            if (upd_num == 0)
            {
                $(this).hide();
            }
        });
    });
    </script>
</body>
</html>