<div class="header-wrapper" name="top">
    <div class="header-content">
        <div class="float-left">
            <table border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td class="header-site-logo" align="left" valign="top">
                    <a href="{{CONFIG_SITE_URL}}" style="margin-left: 10px;">
                        <img src="{{CONFIG_THEME_URL}}/logo.png" alt="{{CONFIG_SITE_NAME}}">
                    </a>
                </td>

                <td align="left" valign="top">
                    <div class="header-live-search">
                        <input value="@header_search_textarea_label@" placeholder="@header_search_textarea_label@" data-placeholder="@header_search_textarea_label@" type="text" onkeyup="SK_headerSearch(this.value);">
                    </div>
                </td>
            </tr>
            </table>
        </div>

        <div class="float-right">
            {{HEADER_NAVIGATION}}
        </div>

        <div class="float-clear"></div>
    </div>
</div>
<div class="dropdown-search-container">
    <div class="dropdown-search-wrapper">
        <div class="dropdown-search-content float-left">
            <div class="search-header">
                <i class="icon-search progress-icon hide"></i>
                @header_search_header_label@
            </div>
            
            <div class="search-list-wrapper"></div>
            
            <div align="center">
                <a class="page-link" href="#">
                    @header_search_all_results_label@
                </a>
            </div>
        </div>
        <div class="float-clear"></div>
    </div>
</div>

{{HEADER_DROPDOWNS}}

{{HEADER_END}}