<div class="footer-wrapper">
    <div class="footer-content" align="center">
        <div class="footer-line">
            <a href="{{ABOUT_PAGE_URL}}" data-href="?tab1=terms&tab2=about">
                @terms_about_label@
            </a> - 
            
            <a href="{{CONTACT_PAGE_URL}}" data-href="?tab1=terms&tab2=contact">
                @terms_contact_label@
            </a> - 
            
            <a href="{{PRIVACY_PAGE_URL}}" data-href="?tab1=terms&tab2=privacy">
                @terms_privacy_label@
            </a> - 
            
            <a href="{{TOS_PAGE_URL}}" data-href="?tab1=terms&tab2=tos">
                @terms_tos_label@
            </a> - 
            
            <a href="{{DISCLAIMER_PAGE_URL}}" data-href="?tab1=terms&tab2=disclaimer">
                @terms_disclaimer_label@
            </a> - 
            
            <a href="{{ADMIN_URL}}">
                @admin_link_label@
            </a>
        </div>
        
        <div class="footer-line">
            @languages_label@: 
            
            {{LANGUAGES}}
        </div>
        
        <div class="footer-line">
            @copyright@ &#169; {{YEAR}} {{CONFIG_SITE_NAME}}. @all_rights_reserved@.
        </div>
    </div>
</div>