<div class="page-margin"></div>
<div class="float-left span25">
    <div class="list-wrapper">
        <div class="list-header">
            @menu_label@
        </div>
        
        <a class="list-column" href="{{TERMS_TOS_URL}}" data-href="?tab1=terms&tab2=tos">
            @terms_tos_label@
        </a>
        
        <a class="list-column" href="{{TERMS_PRIVACY_URL}}" data-href="?tab1=terms&tab2=privacy">
            @terms_privacy_label@
        </a>
        
        <a class="list-column" href="{{TERMS_DISCLAIMER_URL}}" data-href="?tab1=terms&tab2=disclaimer">
            @terms_disclaimer_label@
        </a>
        
        <a class="list-column" href="{{TERMS_CONTACT_URL}}" data-href="?tab1=terms&tab2=contact">
            @terms_contact_label@
        </a>
        
        <a class="list-column" href="{{TERMS_ABOUT_URL}}" data-href="?tab1=terms&tab2=about">
            @terms_about_label@
        </a>
    </div>
</div>

<div class="float-right span74">
    {{TERMS_CONTENT}}
</div>

<div class="float-clear"></div>