<div class="float-left span35">
    {{TIMELINE_BUTTONS}}

    <div class="timeline-sidebar">
        <div class="sidebar-div">
            @page_category_label@: 
            {{CATEGORY_NAME}}
        </div>

        {{INFO_ABOUT_ROW}}

        {{INFO_ADDRESS_ROW}}
        
        {{INFO_AWARDS_ROW}}
        
        {{INFO_PHONE_ROW}}
        
        {{INFO_PRODUCTS_ROW}}
    </div>
</div>